services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: tsmovie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tsmovie-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tsmovie
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - tsmovie-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        CACHEBUST: ${CACHEBUST:-1}
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tsmovie-network

networks:
  tsmovie-network:
    driver: bridge

volumes:
  postgres_data:
