name: Keep Alive Render
on:
  schedule:
    - cron: '*/14 * * * *' # Roda a cada 14 minutos
  workflow_dispatch: # Permite rodar manualmente para testar

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: curl -s https://seu-app-backend.onrender.com/movies # COLOQUE A URL DO SEU BACKEND AQUI